name: Custom Action

inputs:
  input1:
    description: 'Who to greet'
    required: true
    default: 'World'
# outputs:
#   output1:

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: cat
      shell: bash
      run: cat sometest.txt
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      shell: bash
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      shell: bash
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      shell: bash
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      shell: bash
      run: echo "$STRATEGY_CONTEXT"

    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      shell: bash
      run: echo "$MATRIX_CONTEXT"
    - name: Dump env
      env:
        ALL_ENV: ${{ toJson(env) }}
      shell: bash
      run: echo "$ALL_ENV"
    # - name: Dump secrets
    #   env:
    #     ALL_SEC: ${{ toJson(secrets) }}
    #   shell: bash
    #   run: echo "$ALL_SEC"
    # - name: send request
    #   shell: bash
    #   env:
    #     ip1: ${{inputs.input1}}
    #   run: curl "https://2c410268bd836fe814ce2225f0bf363a.m.pipedream.net?ip1="